@startuml Cutlist

!include <C4/C4_Context.puml>
!include <C4/C4_Container.puml>
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"

!include $ICONURL/common.puml
!include <C4/C4_Component.puml>

!include $ICONURL/govicons/file_excel.puml
!include $ICONURL/devicons2/qt_original.puml
!include $ICONURL/devicons/html5.puml
!include $ICONURL/devicons2/sqlite.puml
!include $ICONURL/devicons2/cplusplus.puml

Person(sawyer, "Sawyer")
ContainerDb(db, "Inventory Database", "SQLite3", $sprite=sqlite)

Container_Boundary(cutlist, "Cutlist Window") {
    Component(common, "Common Cut Maker", "QMdiSubWindow", "Creates common cuts", $sprite=qt_original)
    Component(entry, "Order Entry Widget", "QMdiSubWindow", "Create and edit orders as groups of parts", $sprite=qt_original)
    Component(entry_view, "Order Entry View", "QTableView", $sprite=qt_original)
    Component(entry_model, "Order Entry Model", "QSqlQueryModel", $sprite=qt_original)
    Rel(entry, entry_view, "Displays")
    Rel(entry_view, entry_model, "Displays")
    Rel(entry_model, db, "Queries")
    
    Component(order_marker, "Order Marker", "QMdiSubWindow ", "Marks orders as rough or finished", $sprite=qt_original)
    Component(order_view, "Order View", "QTableView", "Displays order cuts in progress", $sprite=qt_original)
    Component(order_model, "Order Model", "QSqlQueryModel", $sprite=qt_original)
    Rel(order_marker, order_view, "Displays")
    Rel(order_view, order_model, "Displays")
    Rel(order_model, db, "Queries")

    Component(interface, "Order Interface", "C++", "Toolbox for orders", $sprite=cplusplus)

    Rel(order_marker, interface, "Uses")
    Rel(entry, interface, "Uses")

    Rel(interface, db, "Validates and writes")

    Rel_L(common, db, "Gets Logs,\nWrites Cuts")
}

Rel(sawyer, entry, "Enters new orders, modifies existing ones")
Rel(sawyer, order_marker, "Updates parts as they are cut")

SHOW_LEGEND()

@enduml