@startuml manufacturing

!include types.puml

interface Persistant {
    +all() : Vector<Self>
    +getId() : uint
    +getById(uint) : Self
    +save(self)
}
Log --|> Persistant

interface Manufacturable {
    +make(Log log) : Self
    +getLog() : Log
    +getManufacturingDimensions() : Dimensions
    +getDimensions() : Dimensions
    +getDrying() : Drying
    +setDrying(Drying)
    +getMaterialsValue() : uint
}
Manufacturable ..> Persistant
Manufacturable ..> Dimensions
Manufacturable ..> Log
Manufacturable ..> Drying

Cookie ..|> Manufacturable
Firewood ..|> Manufacturable
Slab ..|> Manufacturable
Lumber ..|> Manufacturable

@enduml