@startuml types

hide empty members
class Log

package "Products" $product {
    class Cookie
    class Firewood
    class Slab
    class Lumber
}

struct Dimensions {
    +len_eights: uint
    +width_eights: uint
    +height_eights: uint
}

enum Drying {
    AIR_DRIED
    KILN_DRIED
    WET
}

@enduml