@startuml Usecase

actor "Inventory Manager" as inv
== Program Start ==
collections "Inventory Window" as logs
participant "Logs View" as logview
participant "Log Entry" as logentry
queue "Log Manager" as logman
database "Database" as db

logview -> db: Queries and displays

== Log Entry ==

loop Until all logs are entered
    inv -> logentry: Enters log information
    inv -> logentry: Hits submit
    logentry -> logman: Calls
    logman -> logman: Validates\nLog info
    logman -> db: Inserts log
    logman -> logview: Trigger refresh
end

== Log Scrapping ==

inv -> logview : Selects log(s) to scrap
inv -> logs : Hits scrap button
logs -> inv : Requests confirmation
inv -> logs : Confirms
alt Confirmed
logs -> logman : Calls
logman -> db : Deletes log(s)
end

== End ==

@enduml