@startuml sales

actor "Sales Manager" as sales
collections "Sales Page" as generator
database "Database" as db
participant "Host Filesystem" as page

== Program Start ==
generator -> db: Gets products in inventory
sales -> generator: Selects products to put on sale
sales -> generator: Sets amount of each product for sale
generator -> page: Generates product pages

== End ==

@enduml