@startuml sawyer

actor Sawyer as sawyer
collections "Common Cuts" as cuts
collections "Order Editor" as orders
collections "Cutlist" as cutlist
database "Database" as db

== Program Start ==
orders -> db: Gets existing orders
cutlist -> db: Gets first order cuts

== Common Cuts ==
loop Until done
    sawyer -> cuts : Select product to make
    sawyer -> cuts : Selects log to cut from
    cuts -> db : Validates and inserts
end

== Order Entry ==
loop Until all products are ordered
    sawyer -> orders: Enters product information
    sawyer -> orders: Hits submit
    orders -> db: Inserts order
    orders -> orders : Clears form\nand refreshes
    orders -> cutlist : Switches to edited order
    cutlist -> db : Refreshes view
end

== Order Cuts ==
loop Until all cuts are made
    sawyer -> cutlist: Selects order to cut
    sawyer -> cutlist: Selects product to make
    sawyer -> cutlist: Hits submit
    cutlist -> db: Validates and modifies
    cutlist -> cutlist: Refreshes view
end

== End ==

@enduml