name: Ubuntu C/C++ CMAKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Qt      
      uses: jurplel/install-qt-action@v4.1.1
    - name: Create build directory
      run: mkdir build
    - name: Check for CMakeLists.txt
      run: |
        if [ ! -f CMakeLists.txt ]; then
          echo "CMakeLists.txt not found in the repository root"
          exit 1
        fi
    - name: Run CMake
      run: cmake ..
      working-directory: ./build
    - name: Build
      run: make
      working-directory: ./build
