name: Ubuntu C/C++ CMAKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # 2 — Toolchain for docs
    - name: Install Qt + Webengine
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev libqt5webkit5-dev qtwebengine5-dev
        
    - name: Create build directory
      run: mkdir build
    - name: Check for CMakeLists.txt
      run: |
        if [ ! -f CMakeLists.txt ]; then
          echo "CMakeLists.txt not found in the repository root"
          exit 1
        fi
    - name: Dependencies for doxy
      run: sudo apt-get install -y doxygen graphviz
    - name: Run CMake
      run: cmake ..
      working-directory: ./build
    - name: Build
      run: make
      working-directory: ./build
